spring:
  datasource:
    url: jdbc:postgresql://pgvector:5432/postgres
    username: postgres
    password: postgres
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
    ollama:
      base-url: http://jeecg-boot-ollama-1:11434
      chat:
        model: qwen2
      embedding:
        model: mofanke/dmeta-embedding-zh
# springdoc-openapi项目配置`
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bxmdm.ai.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
